Receive timeout
Azure/toketi-kafka-connect-iothub pull request #13
Opened 2018-01-15 19:12 UTC by gdooper

- Adds a new config `ReceiveTimeout` that lets you control the maximum amount of time a PartitionReceiver will attempt to get events from an eventhub.
- Updates the version to 0.6.1

2018-01-15 19:12 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/toketi-kafka-connect-iothub?pullRequest=13) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/toketi-kafka-connect-iothub?pullRequest=13) before we can accept your contribution.<br/><br/>:x: gdooper [sign now](https://cla.opensource.microsoft.com/Azure/toketi-kafka-connect-iothub?pullRequest=13)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/toketi-kafka-connect-iothub?pullRequest=13) it.</sub>

2018-03-09 02:05 UTC, varunpuranik requested changes
While the PR looks good to me, I would like to understand why you are having to set the ReceiveTimeout. Can you please comment on that?

2018-03-09 02:05 UTC, varunpuranik commented on README_Source.md
> +| RequestTimeout | Int | No | 60 | The max duration in seconds to spend receiving entries from IoT Hub. |
ReceiveTimeout

2018-03-09 02:05 UTC, varunpuranik commented on README_Source.md
> +RequestTimeout=60
ReceiveTimeout

2018-03-09 02:05 UTC, varunpuranik commented on connect-iothub-source.properties
> +ReceiveTimeout=60
can we make this ReceiveTimeout

2018-03-09 02:05 UTC, varunpuranik commented on README_Source.md
> +| RequestTimeout | Int | No | 60 | The max duration in seconds to spend receiving entries from IoT Hub. |
Also, the text is a bit confusing (it feels like the connector will stop after the timeout period). Can we reword it to something like - "Max duration to wait when retrieving entities from IoT Hub".

2018-03-09 03:41 UTC, gdooper commented
@varunpuranik In our message pipelines, we have some eventhubs that have messages trickle into the eventhub. Say 1 new message every 10 seconds. We want to keep the latencies in the pipeline as low as possible. Waiting up to 60 seconds for the batch of new events to fill to a count of `BatchSize` is not acceptable for us. Exposing this `ReceiveTimeout` as a config option allows us to reduce the latency without having to reduce the `BatchSize` parameter.

2018-03-09 03:42 UTC, gdooper commented on README_Source.md
> +| RequestTimeout | Int | No | 60 | The max duration in seconds to spend receiving entries from IoT Hub. |
OK, I can fix this.

2018-03-09 03:43 UTC, gdooper commented on README_Source.md
> +RequestTimeout=60
Oops. Will fix.

2018-03-09 05:52 UTC, gdooper commented on README_Source.md
> +| RequestTimeout | Int | No | 60 | The max duration in seconds to spend receiving entries from IoT Hub. |
@varunpuranik For a description, how about `The max duration in seconds to wait for a full batch when retrieving messages from IoT Hub.`

2018-03-09 05:53 UTC, varunpuranik commented on README_Source.md
> +| RequestTimeout | Int | No | 60 | The max duration in seconds to spend receiving entries from IoT Hub. |
Yes, that works..

2018-03-09 05:54 UTC, varunpuranik commented
I see.. makes sense. Thanks for the explanation.

2018-03-09 06:04 UTC, gdooper commented on connect-iothub-source.properties
> +ReceiveTimeout=60
no change necessary here, right?

2018-03-09 17:16 UTC, gdooper commented
@varunpuranik I've updated the PR. Can you review again?

2018-03-10 00:08 UTC, varunpuranik approved these changes

2018-03-10 00:08 UTC, merged